// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Translator
{
    internal sealed partial class Vsix
    {
        public const string Id = "Translator.8bac4de3-f5a2-4d3e-a8d8-a02f2b58ec3d";
        public const string Name = "Translator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
